import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebarWithUser } from "@/components/app-sidebar-with-user"
import { ThemeProvider } from "@/components/theme-provider" 
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebarWithUser />
      <main className="w-full">
        <SiteHeader/>
        {/* <SidebarTrigger className="absolute mt-3 ml-7" /> */}
        <ThemeProvider
          attribute='class'
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="mt-12 px-14">
            {children}
          </div>  
        </ThemeProvider>
      </main>
    </SidebarProvider>
  );
}
